# Generated by Django 5.0.6 on 2024-06-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynotes',
            name='date_update',
        ),
        migrations.AddField(
            model_name='stickynotes',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
